In [42]:

import pandas as pd 
from pathlib import Path
df = pd.read_csv("../FT Data - data.csv")
df.head()

,user_id,recording_id,language,duration,rec_url_gcp,transcription_url_gcp,metadata_url_gcp
0,245746,825780,hi,443,https://storage.googleapis.com/joshtalks-data-...,https://storage.googleapis.com/joshtalks-data-...,https://storage.googleapis.com/joshtalks-data-...
1,291038,825727,hi,443,https://storage.googleapis.com/joshtalks-data-...,https://storage.googleapis.com/joshtalks-data-...,https://storage.googleapis.com/joshtalks-data-...
2,246004,988596,hi,475,https://storage.googleapis.com/joshtalks-data-...,https://storage.googleapis.com/joshtalks-data-...,https://storage.googleapis.com/joshtalks-data-...
3,93626,990175,hi,475,https://storage.googleapis.com/joshtalks-data-...,https://storage.googleapis.com/joshtalks-data-...,https://storage.googleapis.com/joshtalks-data-...
4,286851,526266,hi,522,https://storage.googleapis.com/joshtalks-data-...,https://storage.googleapis.com/joshtalks-data-...,https://storage.googleapis.com/joshtalks-data-...

In [47]:
# here initially (rec_url_gcp) and (transcription_url_gcp) links are in this formate which is not working for us so we need to change it to the working formate that we can download the files using that link
# https://storage.googleapis.com/joshtalks-data-collection/hq_data/hi/967179/825780_audio.wav
# https://storage.googleapis.com/joshtalks-data-collection/hq_data/hi/967179/825780_transcription.json

In [3]:
import requests
import io
import librosa
from datasets import Dataset, Audio
from tqdm import tqdm

In [4]:
# Function to ensure URLs are accessible based on your task instructions
def fix_url(url):
    # Example replacement logic if the 'here' link was broken
    return url.replace("old_link_prefix", "https://storage.googleapis.com/upload_goai")

df['transcription_url_gcp'] = df['transcription_url_gcp'].apply(fix_url)

In [ ]:
import requests

# CHECKING THE FIRST ROW OF THE DATAFRAME TO GET THE URLS FOR AUDIO AND TRANSCRIPTION
audio_url = "https://storage.googleapis.com/upload_goai/967179/825727_audio.wav"
json_url = "https://storage.googleapis.com/upload_goai/967179/825727_transcription.json"

def download_file(url, filename):
    response = requests.get(url)
    if response.status_code == 200:
        with open(filename, 'wb') as f:
            f.write(response.content)
        print(f"Downloaded: {filename}")
    else:
        print(f"Failed to download {url}. Status: {response.status_code}")

download_file(audio_url, "sample_audio1.wav")
download_file(json_url, "sample_transcript1.json")

Downloaded: sample_audio1.wav
Downloaded: sample_transcript1.json

In [50]:
# see we got audio and json file downloaded successfully  
# so now will extract all audio and json files using the same logic and then we will create a dataset in the formate that is required for whisper training

In [51]:
#From original df
df1 = df.loc[: ,"rec_url_gcp"]
df2 = df.loc[: ,"transcription_url_gcp"]

#Create new DataFrame
df3=pd.DataFrame({"audio_url":df1,"transcription_url":df2})

for i in range(len(df3)):  # Processing each row one by one
    temp1 = df3["audio_url"].iloc[i] #Get current URLs
    temp2 = df3["transcription_url"].iloc[i]
# now Split URL 
    sp1 = temp1.split("/")
    sp2 = temp2.split("/")

    base_url = "https://storage.googleapis.com/upload_goai/"

    df3["audio_url"].iloc[i] = base_url + sp1[-2] + "/" + sp1[-1]

    df3["transcription_url"].iloc[i] = base_url + sp2[-2] + "/" + sp2[-1]

df3.loc[:, "audio_url"]
df3.to_csv("fixed_urls.csv", index=False)

C:\Users\rishu\AppData\Local\Temp\ipykernel_16988\626723941.py:17: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df3["audio_url"].iloc[i] = base_url + sp1[-2] + "/" + sp1[-1]
C:\Users\rishu\AppData\Local\Temp\ipykernel_16988\626723941.py:19: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df3["transcription_url"].iloc[i] = base_url + sp2[-2] + "/" + sp2[-1]

In [55]:
fixed_df = pd.read_csv("fixed_urls.csv")
fixed_df.head(3)

,audio_url,transcription_url
0,https://storage.googleapis.com/upload_goai/967...,https://storage.googleapis.com/upload_goai/967...
1,https://storage.googleapis.com/upload_goai/967...,https://storage.googleapis.com/upload_goai/967...
2,https://storage.googleapis.com/upload_goai/114...,https://storage.googleapis.com/upload_goai/114...

In [ ]:
# now we got same formate of URLs for all the audio and json files 
# now download all audio files and json files
# there are 104 total rows in original dataset

In [30]:
from pathlib import Path
import requests

def download_file(url, filename):
    response = requests.get(url)
    if response.status_code == 200:
        with open(filename, 'wb') as f:
            f.write(response.content)
        print(f"Downloaded: {filename}")
    else:
        print(f"Failed to download {url}. Status: {response.status_code}")

audio_base_path = Path("../audio_data")
audio_base_path.mkdir(parents=True, exist_ok=True)

trans_base_path = Path("../transcript_data")
trans_base_path.mkdir(parents=True, exist_ok=True)

for i in range(len(df3)):
    audio_file = audio_base_path / f"sample_audio_{i}.wav"
    trans_file = trans_base_path / f"sample_transcript_{i}.json"

    download_file(df3.loc[i, "audio_url"], audio_file)
    download_file(df3.loc[i, "transcription_url"], trans_file)

Downloaded: ..\audio_data\sample_audio_0.wav
Downloaded: ..\transcript_data\sample_transcript_0.json
Downloaded: ..\audio_data\sample_audio_1.wav
Downloaded: ..\transcript_data\sample_transcript_1.json
Downloaded: ..\audio_data\sample_audio_2.wav
Downloaded: ..\transcript_data\sample_transcript_2.json
Downloaded: ..\audio_data\sample_audio_3.wav
Downloaded: ..\transcript_data\sample_transcript_3.json
Downloaded: ..\audio_data\sample_audio_4.wav
Downloaded: ..\transcript_data\sample_transcript_4.json
Downloaded: ..\audio_data\sample_audio_5.wav
Downloaded: ..\transcript_data\sample_transcript_5.json
Downloaded: ..\audio_data\sample_audio_6.wav
Downloaded: ..\transcript_data\sample_transcript_6.json
Downloaded: ..\audio_data\sample_audio_7.wav
Downloaded: ..\transcript_data\sample_transcript_7.json
Downloaded: ..\audio_data\sample_audio_8.wav
Downloaded: ..\transcript_data\sample_transcript_8.json
Downloaded: ..\audio_data\sample_audio_9.wav
Downloaded: ..\transcript_data\sample_transcript_9.json
Downloaded: ..\audio_data\sample_audio_10.wav
Downloaded: ..\transcript_data\sample_transcript_10.json
Downloaded: ..\audio_data\sample_audio_11.wav
Downloaded: ..\transcript_data\sample_transcript_11.json
Downloaded: ..\audio_data\sample_audio_12.wav
Downloaded: ..\transcript_data\sample_transcript_12.json
Downloaded: ..\audio_data\sample_audio_13.wav
Downloaded: ..\transcript_data\sample_transcript_13.json
Downloaded: ..\audio_data\sample_audio_14.wav
Downloaded: ..\transcript_data\sample_transcript_14.json
Downloaded: ..\audio_data\sample_audio_15.wav
Downloaded: ..\transcript_data\sample_transcript_15.json
Downloaded: ..\audio_data\sample_audio_16.wav
Downloaded: ..\transcript_data\sample_transcript_16.json
Downloaded: ..\audio_data\sample_audio_17.wav
Downloaded: ..\transcript_data\sample_transcript_17.json
Downloaded: ..\audio_data\sample_audio_18.wav
Downloaded: ..\transcript_data\sample_transcript_18.json
Downloaded: ..\audio_data\sample_audio_19.wav
Downloaded: ..\transcript_data\sample_transcript_19.json
Downloaded: ..\audio_data\sample_audio_20.wav
Downloaded: ..\transcript_data\sample_transcript_20.json
Downloaded: ..\audio_data\sample_audio_21.wav
Downloaded: ..\transcript_data\sample_transcript_21.json
Downloaded: ..\audio_data\sample_audio_22.wav
Downloaded: ..\transcript_data\sample_transcript_22.json
Downloaded: ..\audio_data\sample_audio_23.wav
Downloaded: ..\transcript_data\sample_transcript_23.json
Downloaded: ..\audio_data\sample_audio_24.wav
Downloaded: ..\transcript_data\sample_transcript_24.json
Downloaded: ..\audio_data\sample_audio_25.wav
Downloaded: ..\transcript_data\sample_transcript_25.json
Downloaded: ..\audio_data\sample_audio_26.wav
Downloaded: ..\transcript_data\sample_transcript_26.json
Downloaded: ..\audio_data\sample_audio_27.wav
Downloaded: ..\transcript_data\sample_transcript_27.json
Downloaded: ..\audio_data\sample_audio_28.wav
Downloaded: ..\transcript_data\sample_transcript_28.json
Downloaded: ..\audio_data\sample_audio_29.wav
Downloaded: ..\transcript_data\sample_transcript_29.json
Downloaded: ..\audio_data\sample_audio_30.wav
Downloaded: ..\transcript_data\sample_transcript_30.json
Downloaded: ..\audio_data\sample_audio_31.wav
Downloaded: ..\transcript_data\sample_transcript_31.json
Downloaded: ..\audio_data\sample_audio_32.wav
Downloaded: ..\transcript_data\sample_transcript_32.json
Downloaded: ..\audio_data\sample_audio_33.wav
Downloaded: ..\transcript_data\sample_transcript_33.json
Downloaded: ..\audio_data\sample_audio_34.wav
Downloaded: ..\transcript_data\sample_transcript_34.json
Downloaded: ..\audio_data\sample_audio_35.wav
Downloaded: ..\transcript_data\sample_transcript_35.json
Downloaded: ..\audio_data\sample_audio_36.wav
Downloaded: ..\transcript_data\sample_transcript_36.json
Downloaded: ..\audio_data\sample_audio_37.wav
Downloaded: ..\transcript_data\sample_transcript_37.json
Downloaded: ..\audio_data\sample_audio_38.wav
Downloaded: ..\transcript_data\sample_transcript_38.json
Downloaded: ..\audio_data\sample_audio_39.wav
Downloaded: ..\transcript_data\sample_transcript_39.json
Downloaded: ..\audio_data\sample_audio_40.wav
Downloaded: ..\transcript_data\sample_transcript_40.json
Downloaded: ..\audio_data\sample_audio_41.wav
Downloaded: ..\transcript_data\sample_transcript_41.json
Downloaded: ..\audio_data\sample_audio_42.wav
Downloaded: ..\transcript_data\sample_transcript_42.json
Downloaded: ..\audio_data\sample_audio_43.wav
Downloaded: ..\transcript_data\sample_transcript_43.json
Downloaded: ..\audio_data\sample_audio_44.wav
Downloaded: ..\transcript_data\sample_transcript_44.json
Downloaded: ..\audio_data\sample_audio_45.wav
Downloaded: ..\transcript_data\sample_transcript_45.json
Downloaded: ..\audio_data\sample_audio_46.wav
Downloaded: ..\transcript_data\sample_transcript_46.json
Downloaded: ..\audio_data\sample_audio_47.wav
Downloaded: ..\transcript_data\sample_transcript_47.json
Downloaded: ..\audio_data\sample_audio_48.wav
Downloaded: ..\transcript_data\sample_transcript_48.json
Downloaded: ..\audio_data\sample_audio_49.wav
Downloaded: ..\transcript_data\sample_transcript_49.json
Downloaded: ..\audio_data\sample_audio_50.wav
Downloaded: ..\transcript_data\sample_transcript_50.json
Downloaded: ..\audio_data\sample_audio_51.wav
Downloaded: ..\transcript_data\sample_transcript_51.json
Downloaded: ..\audio_data\sample_audio_52.wav
Downloaded: ..\transcript_data\sample_transcript_52.json
Downloaded: ..\audio_data\sample_audio_53.wav
Downloaded: ..\transcript_data\sample_transcript_53.json
Downloaded: ..\audio_data\sample_audio_54.wav
Downloaded: ..\transcript_data\sample_transcript_54.json
Downloaded: ..\audio_data\sample_audio_55.wav
Downloaded: ..\transcript_data\sample_transcript_55.json
Downloaded: ..\audio_data\sample_audio_56.wav
Downloaded: ..\transcript_data\sample_transcript_56.json
Downloaded: ..\audio_data\sample_audio_57.wav
Downloaded: ..\transcript_data\sample_transcript_57.json
Downloaded: ..\audio_data\sample_audio_58.wav
Downloaded: ..\transcript_data\sample_transcript_58.json
Downloaded: ..\audio_data\sample_audio_59.wav
Downloaded: ..\transcript_data\sample_transcript_59.json
Downloaded: ..\audio_data\sample_audio_60.wav
Downloaded: ..\transcript_data\sample_transcript_60.json
Downloaded: ..\audio_data\sample_audio_61.wav
Downloaded: ..\transcript_data\sample_transcript_61.json
Downloaded: ..\audio_data\sample_audio_62.wav
Downloaded: ..\transcript_data\sample_transcript_62.json
Downloaded: ..\audio_data\sample_audio_63.wav
Downloaded: ..\transcript_data\sample_transcript_63.json
Downloaded: ..\audio_data\sample_audio_64.wav
Downloaded: ..\transcript_data\sample_transcript_64.json
Downloaded: ..\audio_data\sample_audio_65.wav
Downloaded: ..\transcript_data\sample_transcript_65.json
Downloaded: ..\audio_data\sample_audio_66.wav
Downloaded: ..\transcript_data\sample_transcript_66.json
Downloaded: ..\audio_data\sample_audio_67.wav
Downloaded: ..\transcript_data\sample_transcript_67.json
Downloaded: ..\audio_data\sample_audio_68.wav
Downloaded: ..\transcript_data\sample_transcript_68.json
Downloaded: ..\audio_data\sample_audio_69.wav
Downloaded: ..\transcript_data\sample_transcript_69.json
Downloaded: ..\audio_data\sample_audio_70.wav
Downloaded: ..\transcript_data\sample_transcript_70.json
Downloaded: ..\audio_data\sample_audio_71.wav
Downloaded: ..\transcript_data\sample_transcript_71.json
Downloaded: ..\audio_data\sample_audio_72.wav
Downloaded: ..\transcript_data\sample_transcript_72.json
Downloaded: ..\audio_data\sample_audio_73.wav
Downloaded: ..\transcript_data\sample_transcript_73.json
Downloaded: ..\audio_data\sample_audio_74.wav
Downloaded: ..\transcript_data\sample_transcript_74.json
Downloaded: ..\audio_data\sample_audio_75.wav
Downloaded: ..\transcript_data\sample_transcript_75.json
Downloaded: ..\audio_data\sample_audio_76.wav
Downloaded: ..\transcript_data\sample_transcript_76.json
Downloaded: ..\audio_data\sample_audio_77.wav
Downloaded: ..\transcript_data\sample_transcript_77.json
Downloaded: ..\audio_data\sample_audio_78.wav
Downloaded: ..\transcript_data\sample_transcript_78.json
Downloaded: ..\audio_data\sample_audio_79.wav
Downloaded: ..\transcript_data\sample_transcript_79.json
Downloaded: ..\audio_data\sample_audio_80.wav
Downloaded: ..\transcript_data\sample_transcript_80.json
Downloaded: ..\audio_data\sample_audio_81.wav
Downloaded: ..\transcript_data\sample_transcript_81.json
Downloaded: ..\audio_data\sample_audio_82.wav
Downloaded: ..\transcript_data\sample_transcript_82.json
Downloaded: ..\audio_data\sample_audio_83.wav
Downloaded: ..\transcript_data\sample_transcript_83.json
Downloaded: ..\audio_data\sample_audio_84.wav
Downloaded: ..\transcript_data\sample_transcript_84.json
Downloaded: ..\audio_data\sample_audio_85.wav
Downloaded: ..\transcript_data\sample_transcript_85.json
Downloaded: ..\audio_data\sample_audio_86.wav
Downloaded: ..\transcript_data\sample_transcript_86.json
Downloaded: ..\audio_data\sample_audio_87.wav
Downloaded: ..\transcript_data\sample_transcript_87.json
Downloaded: ..\audio_data\sample_audio_88.wav
Downloaded: ..\transcript_data\sample_transcript_88.json
Downloaded: ..\audio_data\sample_audio_89.wav
Downloaded: ..\transcript_data\sample_transcript_89.json
Downloaded: ..\audio_data\sample_audio_90.wav
Downloaded: ..\transcript_data\sample_transcript_90.json
Downloaded: ..\audio_data\sample_audio_91.wav
Downloaded: ..\transcript_data\sample_transcript_91.json
Downloaded: ..\audio_data\sample_audio_92.wav
Downloaded: ..\transcript_data\sample_transcript_92.json
Downloaded: ..\audio_data\sample_audio_93.wav
Downloaded: ..\transcript_data\sample_transcript_93.json
Downloaded: ..\audio_data\sample_audio_94.wav
Downloaded: ..\transcript_data\sample_transcript_94.json
Downloaded: ..\audio_data\sample_audio_95.wav
Downloaded: ..\transcript_data\sample_transcript_95.json
Downloaded: ..\audio_data\sample_audio_96.wav
Downloaded: ..\transcript_data\sample_transcript_96.json
Downloaded: ..\audio_data\sample_audio_97.wav
Downloaded: ..\transcript_data\sample_transcript_97.json
Downloaded: ..\audio_data\sample_audio_98.wav
Downloaded: ..\transcript_data\sample_transcript_98.json
Downloaded: ..\audio_data\sample_audio_99.wav
Downloaded: ..\transcript_data\sample_transcript_99.json
Downloaded: ..\audio_data\sample_audio_100.wav
Downloaded: ..\transcript_data\sample_transcript_100.json
Downloaded: ..\audio_data\sample_audio_101.wav
Downloaded: ..\transcript_data\sample_transcript_101.json
Downloaded: ..\audio_data\sample_audio_102.wav
Downloaded: ..\transcript_data\sample_transcript_102.json
Downloaded: ..\audio_data\sample_audio_103.wav
Downloaded: ..\transcript_data\sample_transcript_103.json

In [ ]:
# all downloaded
# now we will create a dataset ready for Whisper training

In [41]:
import os
import json
import librosa
import soundfile as sf
import re
from pathlib import Path

AUDIO_DIR = Path("../audio_data")
TRANSCRIPT_DIR = Path("../transcript_data")
OUTPUT_DIR = Path("../dataset/chunks")

os.makedirs(OUTPUT_DIR, exist_ok=True)

def clean_text(text):
    text = re.sub(r'\b(\w+)( \1\b)+', r'\1', text)
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

dataset = []

for file in os.listdir(AUDIO_DIR):
    if not file.endswith(".wav"):
        continue
    
    # extract index
    index = file.replace("sample_audio_", "").replace(".wav", "")

    # build correct json filename
    json_file = f"sample_transcript_{index}.json"

    json_path = TRANSCRIPT_DIR / json_file

    print(f"Processing: {file}")

    if not os.path.exists(json_path):
        print(f"❌ Missing JSON for {file}")
        continue

    # Load audio
    y, sr = librosa.load(audio_path, sr=16000)

    # Load transcription
    with open(json_path, "r", encoding="utf-8") as f:
        segments = json.load(f)

    # Create folder for this audio
    audio_name = file.replace(".wav", "")
    audio_chunk_dir = os.path.join(OUTPUT_DIR, audio_name)
    os.makedirs(audio_chunk_dir, exist_ok=True)

    # Process segments
    for i, seg in enumerate(segments):
        start = int(seg["start"] * sr)
        end = int(seg["end"] * sr)

        chunk = y[start:end]

        if len(chunk) == 0:
            continue

        text = clean_text(seg["text"])
        if len(text) < 2:
            continue

        chunk_path = os.path.join(audio_chunk_dir, f"{i}.wav")
        sf.write(chunk_path, chunk, sr)

        dataset.append({
            "audio": chunk_path,
            "text": text
        })

# Save final dataset
with open("../dataset/dataset.json", "w", encoding="utf-8") as f:
    json.dump(dataset, f, ensure_ascii=False, indent=2)

print("✅ Dataset ready for Whisper training!")

Processing: sample_audio_0.wav
Processing: sample_audio_1.wav
Processing: sample_audio_10.wav
Processing: sample_audio_100.wav
Processing: sample_audio_101.wav
Processing: sample_audio_102.wav
Processing: sample_audio_103.wav
Processing: sample_audio_11.wav
Processing: sample_audio_12.wav
Processing: sample_audio_13.wav
Processing: sample_audio_14.wav
Processing: sample_audio_15.wav
Processing: sample_audio_16.wav
Processing: sample_audio_17.wav
Processing: sample_audio_18.wav
Processing: sample_audio_19.wav
Processing: sample_audio_2.wav
Processing: sample_audio_20.wav
Processing: sample_audio_21.wav
Processing: sample_audio_22.wav
Processing: sample_audio_23.wav
Processing: sample_audio_24.wav
Processing: sample_audio_25.wav
Processing: sample_audio_26.wav
Processing: sample_audio_27.wav
Processing: sample_audio_28.wav
Processing: sample_audio_29.wav
Processing: sample_audio_3.wav
Processing: sample_audio_30.wav
Processing: sample_audio_31.wav
Processing: sample_audio_32.wav
Processing: sample_audio_33.wav
Processing: sample_audio_34.wav
Processing: sample_audio_35.wav
Processing: sample_audio_36.wav
Processing: sample_audio_37.wav
Processing: sample_audio_38.wav
Processing: sample_audio_39.wav
Processing: sample_audio_4.wav
Processing: sample_audio_40.wav
Processing: sample_audio_41.wav
Processing: sample_audio_42.wav
Processing: sample_audio_43.wav
Processing: sample_audio_44.wav
Processing: sample_audio_45.wav
Processing: sample_audio_46.wav
Processing: sample_audio_47.wav
Processing: sample_audio_48.wav
Processing: sample_audio_49.wav
Processing: sample_audio_5.wav
Processing: sample_audio_50.wav
Processing: sample_audio_51.wav
Processing: sample_audio_52.wav
Processing: sample_audio_53.wav
Processing: sample_audio_54.wav
Processing: sample_audio_55.wav
Processing: sample_audio_56.wav
Processing: sample_audio_57.wav
Processing: sample_audio_58.wav
Processing: sample_audio_59.wav
Processing: sample_audio_6.wav
Processing: sample_audio_60.wav
Processing: sample_audio_61.wav
Processing: sample_audio_62.wav
Processing: sample_audio_63.wav
Processing: sample_audio_64.wav
Processing: sample_audio_65.wav
Processing: sample_audio_66.wav
Processing: sample_audio_67.wav
Processing: sample_audio_68.wav
Processing: sample_audio_69.wav
Processing: sample_audio_7.wav
Processing: sample_audio_70.wav
Processing: sample_audio_71.wav
Processing: sample_audio_72.wav
Processing: sample_audio_73.wav
Processing: sample_audio_74.wav
Processing: sample_audio_75.wav
Processing: sample_audio_76.wav
Processing: sample_audio_77.wav
Processing: sample_audio_78.wav
Processing: sample_audio_79.wav
Processing: sample_audio_8.wav
Processing: sample_audio_80.wav
Processing: sample_audio_81.wav
Processing: sample_audio_82.wav
Processing: sample_audio_83.wav
Processing: sample_audio_84.wav
Processing: sample_audio_85.wav
Processing: sample_audio_86.wav
Processing: sample_audio_87.wav
Processing: sample_audio_88.wav
Processing: sample_audio_89.wav
Processing: sample_audio_9.wav
Processing: sample_audio_90.wav
Processing: sample_audio_91.wav
Processing: sample_audio_92.wav
Processing: sample_audio_93.wav
Processing: sample_audio_94.wav
Processing: sample_audio_95.wav
Processing: sample_audio_96.wav
Processing: sample_audio_97.wav
Processing: sample_audio_98.wav
Processing: sample_audio_99.wav
✅ Dataset ready for Whisper training!

In [59]:
#now we have our dataset ready in the formate that is required for whisper training or fine-tuning

# {
#   "audio": "path/to/audio.wav",
#   "text": "transcribed sentence"
# }

examples: 

{

    "audio": "..\\dataset\\chunks\\sample_audio_0\\0.wav",

    "text": "अब काफी अच्छा होता है क्योंकि उनकी जनसंख्या बहुत कम दी जा रही है तो हमें उनको देखना था तो एक देखना था मतलब वो तो देखना था लेकिन हमारा प्रोजेक्ट भी था कि जो जन जाती पाई जाती है उधर कि उधर की एरिया में उसके बारे में देखना अब"
    
  },